Description:  Main Template for Transit Gateway Workshop
Parameters:
  EC2KEY:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
Resources:
  VPC01Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EC2KEY: !Ref EC2KEY
      TemplateURL: https://transit-gateway-workshop.s3.cn-northwest-1.amazonaws.com.cn/Nested-Stack-VPC1.yml
      TimeoutInMinutes: 6
      Tags:
        - Key: Name
          Value: VPC01Stack
  VPC02Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EC2KEY: !Ref EC2KEY
      TemplateURL: https://transit-gateway-workshop.s3.cn-northwest-1.amazonaws.com.cn/Nested-Stack-VPC2.yml
      TimeoutInMinutes: 6
      Tags:
        - Key: Name
          Value: VPC02Stack
  VPC03Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EC2KEY: !Ref EC2KEY
      TemplateURL: https://transit-gateway-workshop.s3.cn-northwest-1.amazonaws.com.cn/Nested-Stack-VPC3.yml
      TimeoutInMinutes: 6
      Tags:
        - Key: Name
          Value: VPC03Stack
  VPC04Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPC03Stack
    Properties:
      Parameters:
        EC2KEY: !Ref EC2KEY
      TemplateURL: https://transit-gateway-workshop.s3.cn-northwest-1.amazonaws.com.cn/Nested-Stack-VPC4.yml
      TimeoutInMinutes: 6
      Tags:
        - Key: Name
          Value: VPC04Stack
Outputs:
    JumpServerLogin:
      Description: Use this command to login to EC2
      Value: !GetAtt VPC01Stack.Outputs.EC2Login
    VPC1EC2PrivateIP:
      Description: EC2 Private IP in VPC1
      Value: !GetAtt VPC01Stack.Outputs.VPC1PrivateIP
    VPC2EC2PrivateIP:
      Description: EC2 Private IP in VPC2
      Value: !GetAtt VPC02Stack.Outputs.VPC2PrivateIP
    VPC3EC2PrivateIP:
      Description: EC2 Private IP in VPC3
      Value: !GetAtt VPC03Stack.Outputs.VPC3PrivateIP
    VPC4EC2PrivateIP:
      Description: EC2 Private IP in VPC4
      Value: !GetAtt VPC04Stack.Outputs.VPC4PrivateIP